
insert into ERM_RESOURCE_CONFIG (RSID, VERSION, RESOURCEID, RESOURCENAME, ACTIONPATH, WEBMODULEID, MEMO, ISOPEN, STATE, REQUIRESHTTPS, PARENTID, TYPE)
values (1110, 0, 'pkg_KNOWLEDGE', '知识管理', '', 1000, null, 'true', null, null, null, 'pkg');

insert into ERM_RESOURCE_CONFIG (RSID, VERSION, RESOURCEID, RESOURCENAME, ACTIONPATH, WEBMODULEID, MEMO, ISOPEN, STATE, REQUIRESHTTPS, PARENTID)
values (1271, 0, 'function_workflow_store_manage', '知识管理员', '', 1000, null, 'true', null, null, 1110);

insert into ERM_FUNCPERMISSION (OID, VERSION, AUTHORITYCODE, AUTHORITYNAME, AUTHORITYTYPE, RSID, AUTHORITYOID, EXPIREDATE, GRANTABLE, STARRED, CREATEBY, LASTMODIFYBY, AUTHZTIME, REMARK)
values (1303, 0, 'admin', '超级管理员', 'USER', 1271, 1, null, null, null, 'admin', null, null, null);

commit;