insert into ERM_FUNCPERMISSION (OID, VERSION, AUTHORITYCODE, AUTHORITYNAME, AUTHORITYTYPE, RSID, AUTHORITYOID, EXPIREDATE, GRANTABLE, STARRED, CREATEBY, LASTMODIFYBY, AUTHZTIME, REMARK)
select 1200, 0, 'admin', '超级管理员', 'USER', 1402, 1, null, null, null, 'admin', null, systimestamp, null from dual;

insert into ERM_FUNCPERMISSION (OID, VERSION, AUTHORITYCODE, AUTHORITYNAME, AUTHORITYTYPE, RSID, AUTHORITYOID, EXPIREDATE, GRANTABLE, STARRED, CREATEBY, LASTMODIFYBY, AUTHZTIME, REMARK)
select 1201, 0, 'sysAdmin', '系统管理角色', 'ROLE', 1402, 3, null, null, null, 'admin', null, systimestamp, null from dual;

commit;
